<a href="https://colab.research.google.com/github/LWH4Data/Study-code/blob/main/Python_Numpy_Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. 1 rank array

In [ ]:
import numpy as np

# 무작위 다섯 개의 수를 추출
a = np.random.randn(5)

In [ ]:
print(a)

[-0.32624035  3.40233875  0.78905115 -0.36888023 -0.02054533]


In [ ]:
print(a.shape)

(5,)


In [ ]:
# 전치를 하여도 결과는 동일하다 (1 rank array).
a_trans = a.T
print(a_trans)
print(a_trans.shape)


[-0.32624035  3.40233875  0.78905115 -0.36888023 -0.02054533]
(5,)


In [ ]:
print(np.dot(a, a_trans))

12.441438167636154


---


### 2. column vector

In [ ]:
a = np.random.randn(5, 1)
print(a)

[[ 0.90814566]
 [ 0.51969748]
 [-0.95299717]
 [ 0.66712388]
 [ 0.84141075]]


In [ ]:
# 전치시 행벡터로 변환된다.
print(a.T)

[[ 0.90814566  0.51969748 -0.95299717  0.66712388  0.84141075]]


In [ ]:
# 내적결과 행렬이 출력력된다.
print(np.dot(a, a.T))

[[ 0.82472854  0.47196101 -0.86546025  0.60584565  0.76412352]
 [ 0.47196101  0.27008547 -0.49527022  0.34670259  0.43727904]
 [-0.86546025 -0.49527022  0.90820361 -0.63576717 -0.80186207]
 [ 0.60584565  0.34670259 -0.63576717  0.44505427  0.5613252 ]
 [ 0.76412352  0.43727904 -0.80186207  0.5613252   0.70797205]]


---

### 3. shape 확인 및 수정

In [ ]:
# assert 함수를 통해 특정 조건을 만족하는지 확인할 수 있다. (필요시 메시지 출려도 가능).
assert(a.shape == (5,1))

In [ ]:
# reshape()을 통해 수정이 가능하다.
a = a.reshape((5,1))